define({
	/**
	 * 新加国际化字段时,为保证页面文案的独立性,按照页面定义key,且该页面里的所有国际化字段的key都有页面前缀.
	 * (本规则除公共的以外)
	 * 例如:标签分类的key   "tagCate+自定义":"value"
	 */
	//public
	"status": "Status",
	"calcStatus": "Calculated state",
	"search": "Search",
	"creator": "Create person",
	"createTime": "Creation time",
	"reset": "Reset",
	"operation": "Operation",
	"edit": "edit",
	"toDelete": "delete",
	"log": "log",
	"moveUp": "move up",
	"moveDown": "move down",
	"lookUp": "Look up",
	"pleaseSelect": "Please select",
	"pleaseInput": "Please input",
	"save": "Save",
	"noSave":"No save",
	"cancel": "Cancel",
	"buildJson": "Generate JSON",
	"recalculate": "Recalculation",
	"describe":"describe",
	"noData":"No data",
	"remove":"Remove",
	"rename":"Rename",
	"confirmDelete":"Sure you want to delete",
	
	
	//标签定义--html
	"addBasicTag":"Add basic tag",
	"editBasicTag":"Edit basic tag",
	"labelDefinition": "Add basic tag",
	"tagName": "Tag name",
	"touchPointTypes": "Population type",
	"tagSources": "Label source",
	"tagType": "Tag type",
	"changeTagDataTime": "Population update time",
	"allTags": "All tags",
	"backTagList": "Return basic tag list",
	"tagNameMaxLength": "Tag name supports up to 256 characters",
	"tagCategory": "Tag category",
	"uiData": "UI data",
	"serverData": "Server data",
	"searchCritera": "Search criteria",
	"inputKeyword": "Please enter a keyword",
	"populationAttributes": "Population attributes",
	//js
	"noPowerDelOtherTags": "You do not have permission to delete the label created by others.",
	"inputTypeName": "Enter a category name",
	"labelDefinitionList": "Basic Tag definition list",
	"confirmDelTags": "Be sure to delete Tags",
	"addTagSuccess": "Label add success",
	"editTagSuccess": "Label editing success",
	"inputTagName": "Please enter a label name",
	"createCrowdAttrOrHavior": "Create a population attribute or crowd behavior condition",
	"onlyZmSzXhx": "Only letters, numbers, and underscores.",
	"tagRecalculateSuccess": "Tag initiates to re calculate the success",
	"tagRecalculateConfirms": "Tag has changed,do you want to save the changes before recalculation?",
	
	//业务标签--html
	"businessTagList":"Business tag list",
	"businessTagName":"Business tag name",
	"backBusinessTagList":"Return business tag list",
	"viewBusinessTag":"View business tag",
	"addBusinessTag":"Add business tag",
	"editBusinessTag":"Edit business tag",
	"businessTagNameRequire":"Business tag name supports up to 256 characters",
	"createBusinessTag": "Please create the conditions for the business tag.",
	
	//系统标签--html
	"systemTagList":"System tag list",
	"addSystemTag":"Add system tag",
	"systemTagName":"System Tag Name",
	"backSystemTagList":"Return system tags",
	"viewSysTemTag":"View system tag",
	"addSystemTag":"Add system tag",
	"editSystemTag":"Edit system tag",
	"systemTagNameRequire":"System tag name supports up to 256 characters",
	"selectTouchPointTypes":"Please select the type of crowd",
	"calculationScript":"Calculation script",
	"selectCalculationScript":"Please select the calculation script",
	"operatingParameters":"Operating parameters",
	"scriptParamRequire":'Note: the script must be placed on the TD Batch Executor machine, and Executor has permission to access the script file (including the file directory and file that the script will access) (Manager) Script parameters: -a #${paramName1}# -b #{paramName2}#, parameters do not appear"".',
	"inputOperatingParameters":"Please enter operating parameters",
	"describeRequire":"Description supports up to 512 characters",
	//js
	"confirmDelSysTags":"Identify the system labels to be deleted",
	"noRecalculate":"Task is executing, cannot recalculate",
	"systemTagAddSuccess":"System tab to add success",
	"systemTagEditSuccess":"System label editing success",
	"inputSystemTagName":"Please enter the system label name",
	"countingAgainLater":"Re counting, please try again later",
	"systemTagCalcuSuccess":"System tag initiated recalculation success",
	
	//标签分类--html
	"tagCateRmTag":"Remove Tag",
	"tagCateCategory":"Classification",
	"tagCateTagCategory":"Tag classification",
	"tagCateBasicInfo":"Basic information",
	"tagCateCateName":"Category name",
	"tagCateNumOfSubCates":"Number of sub categories",
	"tagCateTagNum":"Tag number",
	"tagCateSameTagPct":"Class label percentage",
	"tagPctOfSubTag":"Percentage of sub label",
	"tagCateTag":"Tag",
	"tagCateAddTag":"Add tag",
	"tagCateCurrentCate":"Current classification",
	"tagCateSeledTags":"Selected tags",
	"tagCateSelTag":"Select tag",
	"tagCateTagNamePrompt":"Please enter the label name, enter the end can enter confirmation",
	"tagCateAddCate":"Add category",
	"tagCateEditCate":"Edit category",
	"tagCatePreCate":"Category parent",
	"tagCateSelPreCate":"Please select the superior classification",
	"tagCateNameUp12":"Category name supports up to 12 characters",
	"tagCateInCateName":"Please enter a category name",
	"tagCateIsPortrait":"Whether it can be used as a portrait of the crowd",
	"tagCateIsPortraitDesc":"After the election, this classification can be displayed in the crowd portrait",
	"tagCateIsTag":"Whether it can be used as a label",
	"tagCateIsTagDesc":"After sorting, this classification can be used as a label",
	"tagCateConfigNextLevel":"The next level of content",
	"tagCateConfigCalcScript":"Generated by script",
	"tagCateIsAutoTag":"Whether to use automatic Tags",
	"tagCateIsAutoTagDesc":"This attribute can be used as a label directly after the check",
	"tagCateAccOrAccAttr":"Account or account properties",
	"tagCateAttr":"attribute",
	"tagCateRunParam":"Operating parameters",
	
	/*人群洞察配置*/
	"backCrowdPortraitGroupList":"Return portrait group list",
	"addCrowdPortrait":"Add a portrait",
	"editCrowdPortrait":"Edit a portrait",
	"crowdPortraitList":"Portrait list",
	"addCommonCrowdPortraitGroup":"Add a common portrait group",
	"addPositionCrowdPortraitGroup":"Add a geographical position portrait group",
	"addCrowdPortraitGroup":"Add a portrait group",
	"editCrowdPortraitGroup":"Edit a portrait group",
	"crowdPortraitGroupList":"Portrait group list",
	"crowdPortraitGroupName":"Portrait group name",
	"crowdPortraitGroupType":"Portrait group type",
	"crowdPortraitGroupAccount":"Subordinate account",
	
	//js
	"tagCateUnDel":"Can not delete, please delete first",
	"tahCateSubCategory":"sub ategory",
	"tagCateSelectUp20":"Select up to 20 tabs at a time, save and then operate",
	"tagCateNoRepeatAddTag":"This tag has been added and cannot be added repeatedly",
	"tagCateNoCheckedTag":"This label is not checked, please re-enter",
	"tagCateSelTagThanSave":"Please select the label and then save",
	"tagCateRmTagFromCate":"Make sure to remove labels from the current category",
	"tagCateSelTagThanRm":"Please select tag and then remove",
	"tagCateRmTagSuccess":"Congratulations, successfully removed tag",
	"tagCateSelRmTag":"Select a category to remove tags",
	"tagCateNewSubCate":"New-build sub category",
	"tagCateExistUnDel":"Existing subcategory or label, cannot be deleted!",
	"tagCateNodeNameEmpty":"The node name cannot be empty",
	"tagCateUpFailNodeNameRepeat":"Failed to edit, node name of the same level can not repeat",
	"tagCateSelTagChooseWay":"Tick as a label, you must choose a way",
	"tagCateInRunParam":"Please enter operating parameters",
	
	//TODO:项目整体国际化完成后删除
	"todo": "todo"
});